### ISSUE TITLE
升级到3.0.8以后，似乎不能打开端口

### ISSUE THREAD

**Issue by sunsan05** [koolshare/merlin-ssserver#5]
如题，使用3.0.8版本时。
正确配置完以后，启动SS-Server，发信telnet连接对应端口都是拒绝连接（内网测试也是一样，应该不是ISP封锁端口）
之前没有这个问题的。
路由的防火墙和DMZ等都是关闭状态。

**Comment by wangwayhome** [comment]
我也是

**Comment by sunsan05** [comment]
用shell看了一下，是配置文件里面的端口配置部分有错，改了之后就好了

**Comment by atoyu** [comment]
可以提供修改方法嗎？

**Comment by helllkz** [comment]
现在都降级到1.9了，不过貌似不能用SS流量，能说下配置方法吗@sunsan05

**Comment by semglassie** [comment]
根本不是什么端口问题，是ss-sever编译的问题，根本无法执行

**Comment by tyornado** [comment]
其实上一个版本编译就有问题了

**Comment by cnrat** [comment]
非常确定是编译问题，可执行文件无法执行。

**Comment by yangwudong** [comment]
应该就是编译问题了，略坑，恢复到了1.9了。

**Comment by junny0204** [comment]
3.0.8設定完, 自己用Client連接都沒有成功! 到底是什麼問題?能否提供2.5.6的安裝檔?

**Comment by LesterLyu** [comment]
https://github.com/koolshare/merlin-ssserver/issues/6

**Comment by LeXwDeX** [comment]
我的错。的确是编译问题…
