### ISSUE TITLE
[INFO] 先暂时降级吧，或者安装entware

### ISSUE THREAD

**Issue by LesterLyu** [koolshare/merlin-ssserver#6]
### INFO
先暂时降级成上一个版本吧，我的编译有问题(用entware的toolchain编译的)，只有安装[entware](https://github.com/RMerl/asuswrt-merlin/wiki/Entware)之后才可以使用。我不大会使用asuswrt的toolchain，compile一直有问题。我现在compile出来的无法使用AEAD Ciphers，直接segmentation fault。
>给路由器插个格式化成ext2/ext3分区的u盘，然后ssh连路由器输入命令```entware-setup.sh```，然后还要``` opkg install libev libudns libcares libsodium libmbedtls libpcre```
----

### WARNING
我不是很建议使用旧版本，2.0版本加入了simple-obfs和AEAD Ciphers，可以防止ip被封。现在好像很多人的ip已经被封了。

**Comment by junny0204** [comment]
能否使用軟件中心的離線安裝呢?

**Comment by LesterLyu** [comment]
用软件中心离线安装上一个版本

**Comment by junny0204** [comment]
1. 是安裝entware，就能使用新版的ssserver 嗎？
2. 舊版的，我從history去下載，用離線安裝，但是都顯示沒有找到安裝檔

**Comment by junny0204** [comment]
@LesterLyu 已经安装完entware，也有opkg install libcares，但是3.0.8的ssserver还是无法使用！
请问还有什么办法可以尝试的吗？

**Comment by junny0204** [comment]
在预设的情况下，直接离线安装旧版本(2.5.6)已经有成功连接，用客户端确定能连上！
但是还是希望能用3.0.8版本，才能使用obfs，实在怕IP被封！所以还请大神们帮帮忙！

**Comment by LesterLyu** [comment]
不好意思，我忘记了还需要
```
 opkg install libev libudns libcares libsodium libmbedtls libpcre 
```

**Comment by helllkz** [comment]
admin@R7000-9969:/# opkg install libcares
Unknown package 'libcares'.
Collected errors:
 * opkg_conf_parse_file: /opt/etc/opkg.conf:1: Ignoring invalid line: `k!ӕ·a¢ר¬5Z«稶nbw¿§b9Ԑ'
 * opkg_install_cmd: Cannot install package libcares.
 * opkg_conf_deinit: Couldn't unlink /opt/var/lock/opkg.lock: No such file or directory.
admin@R7000-9969:/# 
没对呢

**Comment by junny0204** [comment]
我已經成功喔！謝謝LesterLyu

**Comment by LesterLyu** [comment]
为什么会有乱码？试试重新安装entware。 @helllkz

**Comment by helllkz** [comment]
我是用的这个帖子的方法安装的
http://koolshare.cn/forum.php?mod=viewthread&tid=35721
@LesterLyu

**Comment by helllkz** [comment]
重新安装了entware就好了

**Comment by junny0204** [comment]
用SSH进去路由器，要怎么手动启动ssserver？
我有发现3.0.8的，如果重开路由器，很容易就不启动了！
都要用离线安装重新安装一次，才能恢复正常
另外一个问题，配置档是存在哪里呢？.json的档案
